kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: code
spec:
   storageClassName: default-storageclass
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi
